definitions:
  sql.NullTime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  user.User:
    properties:
      created:
        $ref: '#/definitions/sql.NullTime'
      deleted:
        $ref: '#/definitions/sql.NullTime'
      email:
        type: string
      name:
        maxLength: 50
        type: string
      password:
        maxLength: 50
        type: string
      userId:
        maxLength: 50
        type: string
    required:
    - created
    - name
    - password
    - userId
    type: object
  wallet.BallanceResponse:
    properties:
      currency:
        type: string
      name:
        type: number
    required:
    - currency
    - name
    type: object
  wallet.Wallet:
    properties:
      ballance:
        type: number
      created:
        $ref: '#/definitions/sql.NullTime'
      currency:
        maxLength: 3
        type: string
      deleted:
        $ref: '#/definitions/sql.NullTime'
      name:
        type: string
      updated:
        $ref: '#/definitions/sql.NullTime'
      userId:
        maxLength: 50
        type: string
      walletId:
        maxLength: 50
        type: string
    required:
    - ballance
    - created
    - currency
    - deleted
    - name
    - updated
    - userId
    - walletId
    type: object
host: localhost:3010
info:
  contact:
    email: josearanciba09@gmail.com
    name: jose aranciba
  description: This is a simple wallet API. you can handle users, wallets and transactions
    between them
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Wallet API
  version: "1.0"
paths:
  /user:
    get:
      consumes:
      - application/json
      description: Finds in DB a user with the userId Parameter provided by cookies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      summary: Gets the logged user
      tags:
      - user
  /user/new:
    post:
      consumes:
      - application/json
      description: before checking if the origin wallet has funds, it sends the declared
        amount to the destination wallet and creates a trnsaction
      parameters:
      - description: string valid
        in: body
        maxLength: 50
        minLength: 1
        name: originId
        schema:
          type: string
      - description: string valid
        in: body
        maxLength: 50
        minLength: 1
        name: destinationId
        schema:
          type: string
      - description: string valid
        in: body
        name: amount
        schema:
          type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/wallet.Wallet'
            type: array
      summary: Sends money from a wallet to another
      tags:
      - user
  /user/wallet/:walletid:
    get:
      consumes:
      - application/json
      description: Finds in DB a wallet with the provided walletid Parameter
      parameters:
      - description: string valid
        in: path
        maxLength: 50
        minLength: 1
        name: walletid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/wallet.Wallet'
            type: array
      summary: Gets a user´s wallet with the wallet´s Id
      tags:
      - user
  /user/wallets:
    get:
      consumes:
      - application/json
      description: Finds every wallet in DB for the logged user using session parameters
      parameters:
      - description: string valid
        in: path
        maxLength: 50
        minLength: 1
        name: walletid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/wallet.Wallet'
              type: array
            type: array
      summary: Gets the user´s wallets with their corresponding data
      tags:
      - user
swagger: "2.0"
